name: CI
on: [pull_request,push]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./testCases

    steps:
        - name: Checkout tools repo
          uses: actions/checkout@v3
          with:
            repository: PruthvirajSingh/Empt
            path: main

        - name: Install dependencies
          run: |
            
            pip install openpyxl
            pip install pytest
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Run tests and generate Allure report
          run: |
            pytest 

#          env:
#            SELENIUM_BROWSER: chrome
#            SELENIUM_DRIVER_EXECUTABLE_PATH: /usr/bin/chromedriver
#        - name: Upload report to GitHub Pages
#          uses: peaceiris/actions-gh-pages@v3
#          with:
#            personal_token: ${{ secrets.PERSONAL_TOKEN }}
#            publish_dir: ./allure-report

