name: Python Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests and generate Allure report
      run: |
        pytest --alluredir=./allure-results
        allure generate ./allure-results --clean -o ./allure-report
      env:
        SELENIUM_BROWSER: chrome
        SELENIUM_DRIVER_EXECUTABLE_PATH: /usr/bin/chromedriver
    - name: Upload report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./allure-report